apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
    providers:
      file:
        filename: "/etc/traefik/dynamic.yaml"
    log:
      level: INFO
  dynamic.yaml: |
    http:
      routers:
        employee:
          rule: "PathPrefix(`/employee/`)"
          service: employee
          entryPoints:
            - web
        attendance:
          rule: "PathPrefix(`/attendance/`)"
          service: attendance
          entryPoints:
            - web
        salary:
          rule: "PathPrefix(`/salary/`)"
          service: salary
          entryPoints:
            - web
        frontend:
          rule: "PathPrefix(`/`)"
          service: frontend
          entryPoints:
            - web
      services:
        employee:
          loadBalancer:
            servers:
              - url: "http://empms-employee:8083"
        attendance:
          loadBalancer:
            servers:
              - url: "http://empms-attendance-db:8081"
        salary:
          loadBalancer:
            servers:
              - url: "http://empms-salary:8080"
        frontend:
          loadBalancer:
            servers:
              - url: "http://empms-frontend:3000"
