apiVersion: v1
kind: Pod
metadata:
  name: empms-webserver
  labels:
    app: empms-webserver
spec:
  containers:
  - name: webserver
    image: traefik:v2.11
    ports:
    - containerPort: 80
      name: web
    - containerPort: 8080
      name: admin
    volumeMounts:
    - name: config
      mountPath: /etc/traefik
  volumes:
  - name: config
    configMap:
      name: traefik-config
