apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: empms-es
  labels:
    app: empms-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-es
  template:
    metadata:
      labels:
        app: empms-es
    spec:
      containers:
      - name: es
        image: 12mrmack/empms-es:v1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: ES_JAVA_OPTS
          value: "-Xmx512m -Xms512m"
        - name: ELASTIC_PASSWORD
          value: "elastic"
        - name: xpack.security.enabled
          value: "false"
        - name: ES_SETTING_XPACK_SECURITY_ENABLED
          value: "false"
