---
- name: Install Java on CentOS
  yum:
    name: java-17-openjdk
    state: present

- name: Download OpenSearch RPM Package
  get_url:
    url: "https://artifacts.opensearch.org/releases/bundle/opensearch/{{ opensearch_version }}/opensearch-{{ opensearch_version }}-linux-x64.rpm"
    dest: /tmp/opensearch.rpm

- name: Install OpenSearch on CentOS
  yum:
    name: /tmp/opensearch.rpm
    state: present
