apiVersion: apps/v1
kind: Deployment
metadata:
  name: empms-db
  labels:
    app: empms-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: empms-db
    spec:
      containers:
      - name: db
        image: 12mrmack/empm-db:v1
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "attendance_db"
