---
version: '3.2'

services:
  empms-es:
    build:
      context: elasticsearch/
    image: 12mrmack/empms-es:v1
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - ot-microservices

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://empms-es:9200"]'
    depends_on:
      - empms-es
    networks:
      - ot-microservices

  empms-db:
    build:
      context: mysql/
    image: 12mrmack/empm-db:v1
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "attendance_db"
    networks:
      - ot-microservices

  empms-attendance:
    build:
      context: attendance/
    image: 12mrmack/empms-attendance:v1
    ports:
      - "8081:8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.empms-attendance.rule=Host(`ot-microservices.opstree.com`) && PathPrefix(`/attendance/`)"
    volumes:
      - type: bind
        source: ./attendance/config.yaml
        target: /app/config.yaml
        read_only: true
    environment:
      CONFIG_FILE: "/app/config.yaml"
#      ELASTIC_APM_SERVICE_NAME: "attendance"
#      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
      ELASTIC_APM_ENABLED: "false"
    networks:
      - ot-microservices
    depends_on:
      - empms-db

  empms-salary:
    build:
      context: salary/
    image: 12mrmack/empms-salary:v1
    ports:
      - "8084:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.empms-salary.rule=Host(`ot-microservices.opstree.com`) && PathPrefix(`/salary/`)"
    environment:
#      ELASTIC_APM_SERVICE_NAME: "salary"
#      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
      SPRING_ELASTICSEARCH_REST_URIS: "empms-es:9200"
      SPRING_ELASTICSEARCH_REST_USERNAME: elastic
      SPRING_ELASTICSEARCH_REST_PASSWORD: elastic
      ELASTIC_APM_ENABLED: "false"
    networks:
      - ot-microservices
    depends_on:
      - empms-es

  empms-employee:
    build:
      context: employee/
    image: 12mrmack/empms-employee:v1
    ports:
      - "8083:8083"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.empms-employee.rule=Host(`ot-microservices.opstree.com`) && PathPrefix(`/employee/`)"
    volumes:
      - type: bind
        source: ./employee/config.yaml
        target: /app/config.yaml
        read_only: true
    environment:
      CONFIG_FILE: "/app/config.yaml"
#      ELASTIC_APM_SERVICE_NAME: "employee"
#      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
      ELASTIC_APM_ENABLED: "false"
    networks:
      - ot-microservices
    depends_on:
      - empms-es

  empms-notification:
    build:
      context: notification/
    image: 12mrmack/empms-notification:v1
    volumes:
      - type: bind
        source: ./notification/config.yaml
        target: /app/config.yaml
        read_only: true
    environment:
      CONFIG_FILE: "/app/config.yaml"
    networks:
      - ot-microservices
    depends_on:
      - empms-es

  empms-frontend:
    build:
      context: frontend/
    image: 12mrmack/empms-frontend:v1
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.empms-frontend.rule=Host(`ot-microservices.opstree.com`) && PathPrefix(`/`)"
      - "traefik.http.services.empms-frontend.loadbalancer.server.port=3000"
    networks:
      - ot-microservices

  empms-traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
    ports:
      - 80:80
      - 8088:8080
    volumes:
      - type: bind
        source: ./traefik/dynamic.yml
        target: /etc/traefik/dynamic.yml
        read_only: true
    depends_on:
      - empms-frontend
      - empms-attendance
      - empms-salary
      - empms-employee
    networks:
      - ot-microservices

networks:
  ot-microservices:
    driver: bridge

volumes:
  elasticsearch:
  mysql:
